### ISSUE TITLE
RuntimeError: CUDA error: out of memory CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

### ISSUE THREAD

**Issue by muxiddin19** [wuhaozhe/style_avatar#18]
Hi! Thanks for your great work!
Hovewer, I faced problem when I run the python demo.py --in_img ./example/example.png --in_audio ./example/example.wav --output_path ./output
Can, you please, give me some tips to overcome this issue?

**Comment by muxiddin19** [comment]
I tried to run on another remote GPU server. When I run the 
python demo.py --in_img [*.png] --in_audio [*.wav] --output_path [path]
I faced another problem:

[ WARN:0@88.525] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('[*.png]'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "demo.py", line 69, in <module>
    im_rgb = im_bgr[:, :, ::-1]
TypeError: 'NoneType' object is not subscriptable

Can your pleaes give some tips, to handle it?

**Comment by muxiddin19** [comment]
After solving this one I faced another one:
uring handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 72, in <module>
    coeff, align_img = face_reconstructor.recon_coeff(np.array([im_bgr]), np.array([lm5]), return_image = True)
  File "/workspace/style_avatar/deep_3drecon/utils.py", line 111, in recon_coeff
    coeff_ = sess.run([self.coeff],feed_dict = {self.images: input_img_array})
  File "/opt/conda/envs/python36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/opt/conda/envs/python36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/conda/envs/python36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/opt/conda/envs/python36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation Squeeze: node Squeeze (defined at /workspace/style_avatar/deep_3drecon/face_decoder.py:24) was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0 ]. Make sure the device specification refers to a valid device.
         [[Squeeze]]

Any suggestions, please?
